config/routes.rb
Rails.application.routes.draw do

  resources :batches
  resources :users
  resources :front_pages

  root 'front_pages#index'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
end

app/models/front_page.rb
class FrontPage < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

  #ryan, use migration to set default value
  #good try
  # add_column :users, :name, :string, :default => 'John Doe'
  #why use migration? Because defaults only need to run once. 
  #http://stackoverflow.com/questions/6167994/assigning-default-value-while-creating-migration-file
  
  # after_initialize :defaults
  # 
  # def defaults
  #   self.name ||= 'John Doe'
  #   self.jobs ||= 'Your job here'
  #   self.facebook ||= '#'
  #   self.github ||= '#'
  #   self.website ||= '#'
  #   self.picture ||= 'johndoe.png'
  #   self.batch_number ||= '1'
  #   self.role ||= 'student'
  #   # self.approved = false if self.approved.nil?
  # 
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:show, :edit, :update, :destroy]

  # GET /batches
  # GET /batches.json
  def index
    @batches = Batch.all
  end

  # GET /batches/1
  # GET /batches/1.json
  def show
  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params)

    respond_to do |format|
      if @batch.save
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      @batch = Batch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_params
      params.require(:batch).permit(:batch_number, :batch_message, :course_type, :start_date, :end_date)
    end
end

app/controllers/front_pages_controller.rb
class FrontPagesController < ApplicationController
  before_action :set_front_page, only: [:show, :edit, :update, :destroy]

  # GET /front_pages
  # GET /front_pages.json
  def index
    @front_pages = FrontPage.all
    @users = User.all
    @batches = Batch.all
  end

  # GET /front_pages/1
  # GET /front_pages/1.json
  def show
  end

  # GET /front_pages/new
  def new
    @front_page = FrontPage.new
  end

  # GET /front_pages/1/edit
  def edit
  end

  # POST /front_pages
  # POST /front_pages.json
  def create
    @front_page = FrontPage.new(front_page_params)

    respond_to do |format|
      if @front_page.save
        format.html { redirect_to @front_page, notice: 'Front page was successfully created.' }
        format.json { render :show, status: :created, location: @front_page }
      else
        format.html { render :new }
        format.json { render json: @front_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /front_pages/1
  # PATCH/PUT /front_pages/1.json
  def update
    respond_to do |format|
      if @front_page.update(front_page_params)
        format.html { redirect_to @front_page, notice: 'Front page was successfully updated.' }
        format.json { render :show, status: :ok, location: @front_page }
      else
        format.html { render :edit }
        format.json { render json: @front_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /front_pages/1
  # DELETE /front_pages/1.json
  def destroy
    @front_page.destroy
    respond_to do |format|
      format.html { redirect_to front_pages_url, notice: 'Front page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_front_page
      @front_page = FrontPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def front_page_params
      params[:front_page]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :jobs, :facebook, :github, :website, :picture, :role, :batch_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/front_pages_helper.rb
module FrontPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/batches/_form.html.erb
<%= form_for(@batch) do |f| %>
  <% if @batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% @batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :batch_number %><br>
    <%= f.number_field :batch_number %>
  </div>
  <div class="field">
    <%= f.label :batch_message %><br>
    <%= f.text_area :batch_message %>
  </div>
  <div class="field">
    <%= f.label :course_type %><br>
    <%= f.text_field :course_type %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form' %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Batches</h1>

<table>
  <thead>
    <tr>
      <th>Batch number</th>
      <th>Batch message</th>
      <th>Course type</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.batch_number %></td>
        <td><%= batch.batch_message %></td>
        <td><%= batch.course_type %></td>
        <td><%= batch.start_date %></td>
        <td><%= batch.end_date %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form' %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Batch number:</strong>
  <%= @batch.batch_number %>
</p>

<p>
  <strong>Batch message:</strong>
  <%= @batch.batch_message %>
</p>

<p>
  <strong>Course type:</strong>
  <%= @batch.course_type %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @batch.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @batch.end_date %>
</p>

<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>

app/views/front_pages/_form.html.erb
<%= form_for(@front_page) do |f| %>
  <% if @front_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@front_page.errors.count, "error") %> prohibited this front_page from being saved:</h2>

      <ul>
      <% @front_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/front_pages/batch.html.erb
<section id="team" class="bg-light-gray">
		<div class="container">
				<% batch_num = 1 %>
				<% what_batch = @batches.find_by_batch_number(batch_num) %>
				<div class="row">
						<div class="col-lg-12 text-center">
								<h2 class="section-heading"><%= "#{what_batch.course_type}" %> - Batch <%= "#{what_batch.batch_number}" %></h2>
								<h3 class="section-subheading text-muted"><%= "#{what_batch.batch_message}" %></h3>
						</div>
				</div>
				<div class="row">
						<!-- Instructor -->
						<% @users.where(:batch_number => 1, :role => 'instructor').each do |user| %>
							<div class="col-sm-6 col-md-4 col-lg-2">
									<div class="team-member">
											<% profile_pic = user.picture %>
											<%= image_tag("team/#{profile_pic}" ,class: "img-responsive img-circle instructor",
												alt: "", style:"border: 7px solid #FFAE00;") %>

											<h4><%= user.name %></h4>
											<p class="text-muted"><%= user.jobs %></p>
											<ul class="list-inline social-buttons">
													<li><a target="_blank" href="<%= user.facebook %>"><i class="fa fa-facebook"></i></a>
													</li>
													<li><a target="_blank" href="<%= user.github %>"><i class="fa fa-github"></i></a>
													</li>
													<li><a target="_blank" href="<%= user.website %>"><i class="fa fa-globe"></i></a>
													</li>
											</ul>
									</div>
							</div>
						<% end %>
						<!-- Students -->
						<% @users.where(:batch_number => 1, :role => 'student').each do |user| %>
							<div class="col-sm-6 col-md-4 col-lg-2">
									<div class="team-member">
											<% profile_pic = user.picture %>
											<%= image_tag("team/#{profile_pic}" ,class: "img-responsive img-circle ",  alt: "") %>

											<h4><%= user.name %></h4>
											<p class="text-muted"><%= user.jobs %></p>
											<ul class="list-inline social-buttons">
													<li><a target="_blank" href="<%= user.facebook %>"><i class="fa fa-facebook"></i></a>
													</li>
													<li><a target="_blank" href="<%= user.github %>"><i class="fa fa-github"></i></a>
													</li>
													<li><a target="_blank" href="<%= user.website %>"><i class="fa fa-globe"></i></a>
													</li>
											</ul>
									</div>
							</div>
						<% end %>
				</div>
				<div class="row">
						<div class="col-lg-8 col-lg-offset-2 text-center">
								<p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
						</div>
				</div>
		</div>
</section>

app/views/front_pages/edit.html.erb
<h1>Editing Front Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @front_page %> |
<%= link_to 'Back', front_pages_path %>

app/views/front_pages/new.html.erb
<h1>New Front Page</h1>

<%= render 'form' %>

<%= link_to 'Back', front_pages_path %>

app/views/front_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_front_page_path(@front_page) %> |
<%= link_to 'Back', front_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Coding Shop House</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

</head>

  <%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :jobs %><br>
    <%= f.text_field :jobs %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br>
    <%= f.text_area :facebook %>
  </div>
  <div class="field">
    <%= f.label :github %><br>
    <%= f.text_area :github %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_area :picture %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :batch_number %><br>
    <%= f.number_field :batch_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Jobs</th>
      <th>Facebook</th>
      <th>Github</th>
      <th>Website</th>
      <th>Picture</th>
      <th>Role</th>
      <th>Batch number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.jobs %></td>
        <td><%= user.facebook %></td>
        <td><%= user.github %></td>
        <td><%= user.website %></td>
        <td><%= user.picture %></td>
        <td><%= user.role %></td>
        <td><%= user.batch_number %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Jobs:</strong>
  <%= @user.jobs %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @user.facebook %>
</p>

<p>
  <strong>Github:</strong>
  <%= @user.github %>
</p>

<p>
  <strong>Website:</strong>
  <%= @user.website %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @user.picture %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<p>
  <strong>Batch number:</strong>
  <%= @user.batch_number %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>